---

- name: Pre-install | Check token
  when: influxdb_api.token == None or influxdb_api.token | length != 88
  fail: msg="influxdb_api.token must be valid, given value is '{{ influxdb_api.token }}'"

- name: Pre-install | Ping InfluxDB
  register: influxdb_ping
  uri:
    url: "{{ influxdb_api.endpoint }}/api/v2/ping"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"

- name: Pre-install | Set local facts
  set_fact:
      buckets_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.buckets }}"
      authorizations_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.authorizations }}"
      orgs_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.orgs }}"
      scrapers_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.scrapers }}"

- name: Pre-install | Get existing orgs
  register: orgs_ws_result
  uri:
    url: "{{ orgs_endpoint }}"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"

- name: Pre-install | Get existing buckets
  register: buckets_ws_result
  uri:
    url: "{{ buckets_endpoint }}"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"

- name: Pre-install | Get existing scrapers
  register: scrapers_ws_result
  uri:
    url: "{{ scrapers_endpoint }}"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"

- name: Pre-install | Set local facts
  set_fact:
      buckets: "{{ buckets_ws_result.json.buckets }}"
      orgs: "{{ orgs_ws_result.json.orgs }}"
      scrapers: "{{ scrapers_ws_result.json.configurations | default([]) }}"
